
services:
  backend:
    build: .
    container_name: node-backend
    ports:
      - "8080:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    # To run multiple replicas in production, use Docker Swarm or another orchestrator.
    # The following 'deploy' section is used by Swarm and will be ignored by plain docker-compose.
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure

  db:
    image: postgres:16
    container_name: postgres-db
    environment:  # ✅ Corrección aquí
      POSTGRES_DB: indehdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "00000"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
