services:
  backend:
    build: .
    container_name: node-backend
    ports:
      - "8080:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    # Réplicas / deploy removido temporalmente para uso con docker-compose local.

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: indehdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "00000"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
