export class Student {
    constructor(
        public readonly id: string,
        public nombres_apellidos: string,
        public tipo_documento: "CC" | "TI",
        public numero_documento: string,
        public fecha_expedicion_documento: Date,
        public fecha_nacimiento: Date,
        public telefono: string,
        public sexo: "M" | "F",
        public direccion: string,
        public eps: string,
        public tipo_sangre: "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-" | "O+" | "O-",
        public email: string,
        public estado: "Activo" | "Inactivo",
        public fecha_creacion: Date,
        public subsidio: string,
        public categoria: string,
        public modalidad: string,
        public grado: string,
        public discapacidad: string,
        public fecha_modificacion: Date,
        public nombres_apellidos_acudiente: string,
        public numero_documento_acudiente: string,
        public fecha_expedicion_documento_acudiente: Date,
        public telefono_acudiente: string,
        public direccion_acudiente: string,
        public contacto_emergencia: string,
        public empresa_acudiente: string,
        public nombres_apellidos_familiar1: string | null,
        public numero_documento_familiar1: string | null,
        public telefono_familiar1: string | null,
        public parentesco_familiar1: string | null,
        public empresa_familiar1: string | null,
        public nombres_apellidos_familiar2: string | null,
        public numero_documento_familiar2: string | null,
        public telefono_familiar2: string | null,
        public parentesco_familiar2: string | null,
        public empresa_familiar2: string | null,
    ){}
}