export interface CreateStudentDTO {
    nombres_apellidos: string,
    tipo_documento: "CC" | "TI",
    numero_documento: string,
    fecha_expedicion_documento: Date,
    fecha_nacimiento: Date,
    telefono: string,
    sexo: "M" | "F",
    direccion: string,
    eps: string,
    tipo_sangre: "A+" | "A-" | "B+" | "B-" | "AB+" | "AB-" | "O+" | "O-",
    email: string,
    estado: "Activo" | "Inactivo",
    fecha_creacion: Date,
    subsidio: string,
    categoria: string,
    modalidad: string,
    grado: string,
    discapacidad: string,
    fecha_modificacion: Date,
    nombres_apellidos_acudiente: string,
    numero_documento_acudiente: string,
    fecha_expedicion_documento_acudiente: Date,
    telefono_acudiente: string,
    direccion_acudiente: string,
    contacto_emergencia: string,
    empresa_acudiente: string,
    nombres_apellidos_familiar1: string | null,
    numero_documento_familiar1: string | null,
    telefono_familiar1: string | null,
    parentesco_familiar1: string | null,
    empresa_familiar1: string | null,
    nombres_apellidos_familiar2: string | null,
    numero_documento_familiar2: string | null,
    telefono_familiar2: string | null,
    parentesco_familiar2: string | null,
    empresa_familiar2: string | null,
}